# Generated by Django 5.1.4 on 2025-02-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.reservation'),
        ),
    ]
