# Generated by Django 5.1.4 on 2025-03-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
