# Generated by Django 5.1.4 on 2025-01-06 21:31

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('region', models.CharField(choices=[(None, '지역'), ('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('경상', '경상'), ('충청', '충청'), ('전라', '전라'), ('제주', '제주')], default='지역', max_length=50)),
                ('category', models.CharField(choices=[(None, '카테고리'), ('긴급헌혈', '긴급헌혈'), ('궁금해요', '궁금해요'), ('얘기해요', '얘기해요'), ('후기에요', '후기에요')], default='카테고리', max_length=30)),
                ('blood', models.CharField(choices=[(None, '혈액형'), ('전체', '전체'), ('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], default='혈액형', max_length=30)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=community.models.image_upload_path)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=community.models.image_upload_path)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=community.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
