# Generated by Django 5.1.4 on 2025-03-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
