# Generated by Django 5.1.4 on 2025-01-04 15:45

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dog_name', models.CharField(max_length=30)),
                ('dog_age', models.PositiveIntegerField()),
                ('weight', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('neuter', models.BooleanField()),
                ('blood', models.CharField(max_length=30)),
                ('dog_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path)),
                ('represent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
