# Generated by Django 5.1.4 on 2025-01-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='represent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
